baseurl = "http://spf13.com/"
title = "Hacking Management"
languageCode = "en-us"
disqusShortname = "spf13"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
MetaDataFormat = "toml"

[author]
    name = "Steve Francia"

[indexes]
    tag = "tags"
    topic = "topics"

